services:
  db:
    image: postgres:16
    container_name: save_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./backend
    container_name: save_api
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-in-prod}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

volumes:
  db_data:
